name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap Carthage
      run: carthage update --no-use-binaries
    - name: Run tests
      run: xcodebuild test SWIFT_VERSION=5.1 -workspace RxCoreLocation.xcworkspace -scheme 'RxCoreLocation-iOS' -sdk iphonesimulator -destination "name=iPhone 11" | xcpretty -c --test
